rl-institut/spice_ev

- generate_from_simbev.py
Introduced --use-simbev-soc flag in arguments. If set, use SoC generated by SimBEV instead of calculating desired SoC from next trip. Simulate battery to check if charging is feasible.
Minor changes: use vehicle capacity from SimBEV file instead of script if there is a mismatch. Use verbosity level for set_options_from_config.
> generate_from_simbev: can use SimBEV SoC directly

- simulate.py
- src/strategy.py
I added another parser argument in simulate that makes the simulation continue despite negative SoCs.
This PR closes #17
> Feature: allow negative SoC

- src/constants.py
- src/scenario.py
- src/strategies/greedy_market.py
- add VehicleType attribute "v2g" (boolean, default false)
- after GreedyMarket has raised vehicle to safe SoC level within horizon, try to discharge V2G vehicles at highest price points
- can charge again to always leave with desired SoC
> add vehicle-to-grid capability to GreedyMarket

- examples/generate.cfg
- examples/generate_schedule.cfg
- generate.py
- generate_schedule.py
This PR contains two changes that are connected logical way but not technically.
1. The definition and determination procedure of charging priorities for the schedule was changed.
2. The simulation start time can now be set via cmd line and config file.
> New schedule priority definition and simulation start time as cmd param

- src/strategies/balanced_market.py
1. If the current timestep is not part of the balanced charging timespan, do not block that timespan for V2G simulation.
2. Off by one error. If v2g_sorted_idx cannot go never be 0, there will never be discharging at the end of a standing time.       (see screenshots for visualization)
*Before*
*After*
3. As far as I understand, once power was applied the current time step will not be taken into account again during V2G simulation.
> Fix for Balanced Market V2G Oscialltion

- src/strategies/flex_window.py
Fix #Issue
- The power computed for balanced charging is capped at the remaining power of the GC
- Comments describing what the power computed in the `distribute_balanced_vehicle` resembles
@Piranias Does that larger comment added make sense to you or have I misunderstood the code?
@jakobgemassmer During my tests, the simulation fails now due to insufficiently charged vehicles. Also the GC is no longer exceeded in my cases. Could you check your szenarios?
> cap computed charging power in flex_window at remaining GC power

- src/scenario.py
- src/strategies/flex_window.py
- src/strategies/schedule.py
- src/strategy.py
Fix #70 
- The schedule or the charge-windows are now only shown in the first plot if the appropriate strategy is used.
- If neither flex_window or schedule is used, none is shown in the plot.
*Please mark above checkboxes as following:*
> Show schedule or charge-windows only if appropriate strategy is used

- src/strategies/flex_window.py
Fix #76
While looking into the future, the current GC power was affected by future feed-in events. Removed the command, as this does not make sense and it seems not to change charging results.
> GC power now unaffected by future events

- examples/generate.cfg
- generate.py
- tests/test_generate.py
Fix #80 
- Fixed calculation of arrival time for the case that arrival is on next day.
- Set multiple no_drive_dates of vehicles via config file
*Please mark above checkboxes as following:*
> Fix calculation of arrival_time and added no_drive_days to cfg-file

- src/scenario.py
Fix #Issue
- Collect the SOCs after each simulation step indepent of the grid connectors. The state of charge has nothing not tied to a grid connector in any way. 
- Fixes:
- Calculation of disconnected SOCs for vehicles travelling from one GC to a another.
- Different colors in graph for single vehicle for connected and disconnected timesteps.
- Simplified procedure for "save_soc" option 
> stop tracking socs per GC

- doc/source/charging_strategies.rst
- src/strategy.py
Separates functionality of `ALLOW_NEGATIVE_SOC`. Now it is possible to proceed with negative SoC.
> add strategy option RESET_NEGATIVE_SOC

- examples/generate_from_download.cfg
- generate_from_download.py
In addition to input (events.json) and output (scenario.json) paths, generate_from_download now needs a mapping between charging point gates and their corresponding vehicles (or capacities of vehicle). Option `count` is not used anymore.
> generate_from_download uses charging point file

- examples/vehicle_types.json
- src/battery.py
- src/constants.py
- src/scenario.py
- src/strategy.py
- tests/test_strategies.py
All batteries (vehicle and stationary) can have a loss rate. This is a dictionary with the following possible keys:
relative: percentage lost per timestep in relation to the current charge
fixed_relative: percentage lost per timestep in relation to maximum capacity
fixed_absolute: flat amount of energy lost per timestep
Consider a battery with a capacity of 20 kWh and a state of charge (SoC) of 50%.
With a _relative_ loss rate of 10%, the SoC will be 45%.
With a _fixed_relative_ loss rate of 10%, the SoC will be 40%.
With a _fixed_absolute_ loss rate of 10 kWh, the SoC will be 0%.
Empty batteries do not empty further, the minimum is 0% SoC. Batteries that were below 0% will magically "fill" to 0%.
By default, the loss rate is disabled.
> add loss rate to batteries

- examples/generate.cfg
- examples/vehicle_types.json
- generate.py
- tests/test_data/input_test_generate/vehicle_types.json
- removed no_drive_days from cfg file
- added no_drive_days to examples/vehicle_types and tests/test_data/input_test_generate/vehicle_types
- added error message if list of no_drive_days is not provided
> individual no_drive_days for each vehicle_type

- src/generate/generate_from_csv.py
- src/generate/generate_from_statistics.py
Estimated time of departure was fixed to 8h when no further trip was made. This caused problems when the scenario ran for more than 8h still. On the other hand, trips ending right before the end of scenario need an estimated time of departure suitably far into the future. Therefore, the estimated time of departure was changed to be the maximum between the end of the scenario and 8 hours after arrival.
Also, changed scenario definition to use stop_time instead of n_intervals (where the calculation used the stop_time).
> set default est. time of dep. to end of sim instead of 8h

- generate.py
- spice_ev/report.py
- spice_ev/strategy.py
- tests/test_calculate_costs.py
- tests/test_data/input_test_strategies/scenario_PV_Bat.json
- tests/test_generate.py
- tests/test_report.py
- tests/test_strategies.py
- tests/test_util.py
- generate: CSV options truly optional, slight refactoring of CSV code. Test more obscure options
- report: catch empty soc and charging stations while plotting. Test plotting
- strategy: set default PRICE_THRESHOLD of 0, don't reset GC max_power when GC event has no max_power field. More event testing, test low prices
- test schedule with V2G
- util.set_options_from_config: test empty line
> extend test coverage

- calculate_costs.py
- simulate.py
- tests/test_calculate_costs.py
- tests/test_data/input_test_strategies/scenario_A.json
- tests/test_data/input_test_strategies/scenario_C1.json
- tests/test_strategies.py
- only take actual grid supply for cost calculation of fixed load instead of original fixed load
> take actual grid supply for cost calculation of fixed load

- spice_ev/strategies/balanced_market.py
Fixes #175 
- Discharge power for V2G in the balanced_market strategy now considers the charging station power
> Fix v2g discharge power in balanced_market

- spice_ev/generate/generate_schedule.py
- spice_ev/report.py
For GC results, GC timeseries and SoC timeseries. Mostly relevant with Windows, where by default path lengths must not exceed 260 characters.
> show warning if file path length exceeds 260 characters

- spice_ev/battery.py
- tests/test_components.py
In certain cases, the battery Soc approached the charging curve boundary without being able to surpass it (floating point arithmetic). 
Changed: take next interval if SoC is already close to next boundary, stop charging if SoC is close to target (in both cases compare with EPS instead of 0).
Added assertion that energy delta is greater than 0 (something happens in the battery, no infinite loop)
> fix battery problems at CC boundaries

- doc/source/charging_strategies_incentives.rst
- doc/source/code.rst
- doc/source/simulating_with_spiceev.rst
- examples/data/price_sheet.json
- spice_ev/costs.py
- spice_ev/report.py
- spice_ev/strategies/peak_load_window.py
- tests/test_data/input_test_cost_calculation/price_sheet.json
- Added cost calculation for strategy peak_load_window
Still open: TESTS
Should be added before merging into dev.
> cost calculation for strategy peak_load_window

- simulate.py
- spice_ev/report.py
- tests/test_report.py
Make flex band infos in report optional (skips additional flex band computation). Default: flex band is created, same as before. Set `skip_flex_report=true` to disable.
> new flag skip_flex_report

- spice_ev/strategies/peak_load_window.py
- tests/test_calculate_costs.py
Find the balanced power for charging iterativly
Fixes #Issue
- Fix issue with peak_load_window and non constant charging curves
- If non constant charging curves are given, the balanced power is now found iterativly trying to minimize charging during peak_load_windows
> Add peak_load_window case for non-constant charging curves

- calculate_costs.py
- examples/configs/calculate_costs.cfg
- simulate.py
- spice_ev/costs.py
- spice_ev/util.py
- tests/test_calculate_costs.py
- tests/test_util.py
Instead of using charging strategies to determine cost calculation, give type directly. Supported types: fixed_w_plw, fixed_wo_plw, balanced_market, schedule, flex_window. Later, variable_wo_plw and variable_w_plw will be added. 
Customer type (SLP, RLM) can be given, but is optional. If not given, determine using energy supply. 
New util function get_time_windows_from_json to generate time windows column for scenario. 
Various changes to linebreaks and comments for readability.
> refactor costs.py
