rl-institut/spice_ev

- generate_from_simbev.py
Fixes #1
Please merge if you like what you see @stefansc1
> allow for SoC limit to be 0, add warnings

- generate_from_simbev.py
Use `--verbosity` or `-v` to increase verbosity levels in generate_from_simbev.py. Can be given multiple times.
Default: only errors
`-v`: errors and warnings
`-v -v` or `-vv`: debug
> Add verbosity levels to generate_from_simbev

- examples/generate.cfg
- examples/generate_from_simbev.cfg
- examples/scenario.json
- generate.py
- generate_from_simbev.py
- src/battery.py
- src/loading_curve.py
- src/plot_charging.py
- src/scenario.py
- src/strategies/inverse.py
- src/strategies/v2g.py
- src/tests.py
These are breaking changes, old JSON files will not work anymore.
> refactor: SoC between 0 and 1

- src/strategies/balanced.py
- src/strategies/balanced_market.py
- src/strategies/flex_window.py
- src/strategies/greedy.py
- src/strategies/greedy_market.py
- src/strategy.py
@Piranias: Can you have a quick look at the change in flex_window? Just to see if there may be logical issues with the changes I made, that might have escaped my mind.
@stefansc1: All changes made are listed in the PDF attached.
[Reordering of Strategy Options.pdf](https://github.com/rl-institut/spice_ev/files/7693322/Reordering.of.Strategy.Options.pdf)
> Refactoring strategy options

- src/strategies/balanced_market.py
> balanced_market: charge balanced even below price threshold

- doc/source/_static/style.css
- doc/source/conf.py
added static CSS file for RTD pages
> make documentation HTML pages full width

- src/strategies/balanced_market.py
Fix #54
- fixed discrepancy between charging/discharging power and average power usable by GC by running power allocation simulation in the end
-  improved calculation how much power is available for V2G
- fixed update of power vector in case value was already set (e.g., from normal charging)
- improved power allocation (nothing happens for sim_power = 0)
> balanced market V2G fix

- src/strategies/balanced_market.py
Fix #Issue
- Your_changes
*Please mark above checkboxes as following:*
> BM V2G: added derivation comment

- src/strategies/balanced_market.py
> Fix: balanced_market with battery should no longer exceed GC limit

- src/scenario.py
> Feed-in does not exceed GC power limit anymore

- examples/vehicle_types.json
- generate.py
- only vehicle types that are actually present are written to the scenario file
- vehicle type count is no longer written to the scenario file
- fixed typo in example vehicle types
> Fix vehicle type generation

- generate_from_csv.py
- improved logic of assign_vehicle_id
- added sanity check: vehicles can't arrive before departure
- fixed docstring
- removed dependency from bisect
> reworked assign_vehicle_id in generate_from_csv

- generate.py
- generate_from_csv.py
- tests/test_generate.py
- increase delta_soc above min_soc if next trip requires more
- print out number of chargings with increased SoC
- add discharge_limit to arguments (default: 0.5)
implements #96
> add features to generate_from_csv

- src/strategies/schedule.py
Added strategy option `warn_core_standing_time` to schedule strategy. When not set (default), the simulation aborts when a vehicle is not present during the given core_standing_time. When set, a warning is displayed but the simulation continues.
> warn_core_standing_time

- src/report.py
- src/scenario.py
- src/strategy.py
count number of times SoC is below desired SoC on departure, added to results report
> implement #101: margin counter

- src/scenario.py
Save all soc when not driving, not just when connected to charging station. Use estimated_time_of_departure to check if vehicle is standing. Interpolate to last known soc.
> save intermediate soc

- src/strategies/schedule.py
- renamed balanced_vehicle to collective
- removed greedy, needy and balanced
- individual unchanged
- simplified checks, removed unused code blocks
> changed schedule substrategies

- tests/test_data/input_test_generate/example_simbev_run
- tests/test_generate.py
add basic generate_from_simbev testing by looking at example
> test simbev example

- generate_schedule.py
- flex band (collective and individual): include max CS power and max vehicle charging power
- flex band (collective): no charging interval out of core_standing_time
- gen_schedule (collective): added check against empty intervals
> fix generate_schedule

- src/generate/generate_from_csv.py
- src/generate/generate_from_simbev.py
- src/generate/generate_from_statistics.py
- tests/test_generate.py
Extended test_generate: test if resulting scenario can be created, added test with CSV files
> fix include CSV options

- src/generate/generate_from_simbev.py
- at each charge event, both arrival and departure events are added
- estimated_time_of_arrival and desired_soc (for ignore_simbev_soc option) are set when known
- fix off-by-one-error for event start index
- fix possible_energy calculation for charging events longer than 24h
- fix index calculation for ignore_simbev_soc warning when next trip is impossible
- removed post-trip dummy departure
> restructure event generation for generate_from_simbev

- src/battery.py
- src/constants.py
- src/events.py
- src/report.py
- src/scenario.py
- src/strategies/schedule.py
- tests/test_components.py
- tests/test_strategies.py
Battery now actually tries to reach desired schedule instead of prioritizing staying within GC limit (still constricted by GC power limits). Slightly rewritten because of confusing signs.
> better use of stat. batteries in schedule strategy

- calculate_costs.py
- examples/sim_via_function.py
- generate.py
- simulate.py
- spice_ev/battery.py
- spice_ev/components.py
- spice_ev/costs.py
- spice_ev/events.py
- spice_ev/generate/generate_from_csv.py
- spice_ev/generate/generate_from_simbev.py
- spice_ev/generate/generate_from_statistics.py
- spice_ev/generate/generate_schedule.py
- spice_ev/loading_curve.py
- spice_ev/report.py
- spice_ev/scenario.py
- spice_ev/strategies/balanced.py
- spice_ev/strategies/balanced_market.py
- spice_ev/strategies/distributed.py
- spice_ev/strategies/flex_window.py
- spice_ev/strategies/greedy.py
- spice_ev/strategies/peak_load_window.py
- spice_ev/strategies/schedule.py
- spice_ev/strategy.py
- spice_ev/util.py
- tests/test_calculate_costs.py
- tests/test_components.py
- tests/test_strategies.py
- Adjusted docstrings to appear in RTD in correct way.
- Fixed minor typos.
> fix docstrings and typos

- spice_ev/report.py
Fixes #Issue
- Wording in plot is now a little clearer
> minor adjustments to plotting

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CONTRIBUTING.md
- doc/source/conf.py
- setup.py
> Update dev with Release/v1.0.0

- tests/test_strategies.py
test_scenarios just ran simulations without checking if they succeeded.
> check if scenarios actually run through

- spice_ev/strategy.py
- tests/test_strategies.py
Generate a UserWarning if there is an arrival event while the corresponding vehicle is already connected to a charging station. Slight logic change (force unplug on departure, regardless if connected or not). Includes test for generated warning.
> warn if arrival while already at charging station

- spice_ev/strategies/peak_load_window.py
Instead of shortening Peak Load Window's event list, compute timestep index during future event peeks.
> peak load window: static event list
